/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Equipo;
import modelo.Jugador;

/**
 *
 * @author Miguel Ángel
 */
public class Secundaria extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Secundaria() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        rellenarTabla();
    }
    
    public void rellenarTabla() throws SQLException{
        
        DefaultTableModel tablaJugador = (DefaultTableModel) jTableJugadores.getModel();
     
        ArrayList<Jugador> datos;
        datos=controlador.ControladorJugador.mostrarJugadores();
        System.out.println(datos);
        for (int i = 0; i < datos.size(); i++) {
            System.out.println(datos.get(i).getMiEquipo());
            int id= datos.get(i).getId();
            String nombre= datos.get(i).getNombre();
            String nEquipo=controlador.ControladorJugador.nombreEquipo(datos.get(i).getEquipo()) ;
            String apellido=datos.get(i).getApellidos();
            String posicion=datos.get(i).getPosicion();
            double altura=datos.get(i).getAltura();
            double sueldo= datos.get(i).getSueldo();
            Equipo miEquipo=datos.get(i).getMiEquipo();
            
            tablaJugador.addRow(new Object[]{id,nEquipo, nombre, apellido, altura, posicion, sueldo,miEquipo.getId()});

        }
        
           
    
    }
    public void actualizarTabla(){
        try {
            // TODO add your handling code here:
            
        DefaultTableModel tablaJugador = (DefaultTableModel) jTableJugadores.getModel();
            ArrayList<Jugador> datos=new ArrayList<>();
            datos=controlador.ControladorJugador.mostrarJugadores();
                while (tablaJugador.getRowCount() > 0) {
                tablaJugador.removeRow(0);
        }
            rellenarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJugadores = new javax.swing.JTable();
        insertar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        actualizarTabla = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuligas = new javax.swing.JMenu();
        jMenuItemLigas = new javax.swing.JMenuItem();
        equipo = new javax.swing.JMenu();
        jMenuItemEquipos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 40));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jTableJugadores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipo", "Nombre", "Apellido", "Altura", "Posicion", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(jTableJugadores);

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Jugadores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        actualizarTabla.setText("Actualizar Tabla");
        actualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(insertar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(actualizarTabla)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(actualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(66, 35));

        jMenuInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuInicio.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jMenuInicio.setLabel("Inicio");

        jMenuItemInicio.setText("Volver a Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemInicio);

        jMenuBar1.add(jMenuInicio);

        jMenuligas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuligas.setText("Ligas");
        jMenuligas.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jMenuligas.setMargin(new java.awt.Insets(0, 0, 0, 15));
        jMenuligas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuligasActionPerformed(evt);
            }
        });

        jMenuItemLigas.setText("Ir a Ligas");
        jMenuItemLigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLigasActionPerformed(evt);
            }
        });
        jMenuligas.add(jMenuItemLigas);

        jMenuBar1.add(jMenuligas);

        equipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equipo.setText("Equipo");
        equipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        equipo.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        equipo.setMargin(new java.awt.Insets(0, 0, 0, 15));

        jMenuItemEquipos.setText("Ir a Equipos");
        jMenuItemEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquiposActionPerformed(evt);
            }
        });
        equipo.add(jMenuItemEquipos);

        jMenuBar1.add(equipo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        try {
            // TODO add your handling code here:
            InserAct insertar = null;
            String id="";
            String nEquipo="";
            String nombre="";
            String apellidos="";
            String altura="";
            String posicion="";
            String sueldo="";
            
            
            insertar = new InserAct(id,nEquipo,nombre,apellidos,altura,posicion,sueldo);
            insertar.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        int row=jTableJugadores.getSelectedRow();
        
        if (row<0){
            JOptionPane.showMessageDialog(null,"Seleccione un jugador","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        
            try {
                String id = jTableJugadores.getValueAt(row, 0).toString();
                String nEquipo = jTableJugadores.getValueAt(row, 1).toString();
                String nombre = jTableJugadores.getValueAt(row, 2).toString();
                String apellidos = jTableJugadores.getValueAt(row, 3).toString();               
                String altura = jTableJugadores.getValueAt(row, 4).toString();
                String posicion = jTableJugadores.getValueAt(row, 5).toString();
                String sueldo = jTableJugadores.getValueAt(row, 6).toString();
                
                InserAct abrir = new InserAct(id,nEquipo,nombre,apellidos,altura,posicion,sueldo);
                abrir.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void jMenuligasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuligasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuligasActionPerformed
    
    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        // TODO add your handling code here:
        Principal abrir = new Principal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jMenuItemLigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLigasActionPerformed
        try {
            SecundariaL abrir = new SecundariaL();
            abrir.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemLigasActionPerformed

    private void jMenuItemEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquiposActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            SecundariaE abrir = new SecundariaE();
            abrir.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemEquiposActionPerformed

    private void actualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTablaActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_actualizarTablaActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        int row=jTableJugadores.getSelectedRow();
        
        if (row<0){
            JOptionPane.showMessageDialog(null,"Seleccione un jugador","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        String id = jTableJugadores.getValueAt(row, 0).toString();
        controlador.ControladorJugador.borrarJugador(Integer.parseInt(id));
        actualizarTabla();  
            
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Secundaria().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton actualizarTabla;
    private javax.swing.JButton eliminar;
    private javax.swing.JMenu equipo;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemEquipos;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemLigas;
    private javax.swing.JMenu jMenuligas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJugadores;
    // End of variables declaration//GEN-END:variables
}
